version: '3'
services:
  mail:
    image: ixdotai/smtp:v0.5.1
    volumes:
    - ./files/mail/rsa.private:/etc/exim4/dkim.key.temp:ro
    environment:
    - MAILNAME=${DOMAIN}
    - DKIM_KEY_PATH=/etc/exim4/dkim.key.temp
    restart: always
    ports:
    - 25
  service:
    depends_on:
    - secrets
    - mail
    - pyxform
    - enketo
    volumes:
    - secrets:/etc/secrets
    - /data/transfer:/data/transfer
    environment:
    - DOMAIN=${DOMAIN}
    - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
    - HTTPS_PORT=${HTTPS_PORT:-443}
    - NODE_OPTIONS=${SERVICE_NODE_OPTIONS:-}
    - DB_HOST=${DB_HOST:-postgres14}
    - DB_USER=${DB_USER:-odk}
    - DB_PASSWORD=${DB_PASSWORD:-odk}
    - DB_NAME=${DB_NAME:-odk}
    - DB_SSL=${DB_SSL:-null}
    - EMAIL_FROM=${EMAIL_FROM:-no-reply@$DOMAIN}
    - EMAIL_HOST=${EMAIL_HOST:-mail}
    - EMAIL_PORT=${EMAIL_PORT:-25}
    - EMAIL_SECURE=${EMAIL_SECURE:-false}
    - EMAIL_IGNORE_TLS=${EMAIL_IGNORE_TLS:-true}
    - EMAIL_USER=${EMAIL_USER:-}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
    - OIDC_ENABLED=${OIDC_ENABLED:-false}
    - OIDC_ISSUER_URL=${OIDC_ISSUER_URL:-}
    - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-}
    - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-}
    - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
    - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
    - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
    command:
    - wait-for-it
    - ${DB_HOST:-postgres14}:5432
    - --
    - ./start-odk.sh
    restart: always
    logging:
      driver: local
    ports:
    - 8383
    image: ghcr.io/caktus/central-service
  nginx:
    depends_on:
    - service
    - enketo
    environment:
    - DOMAIN=${DOMAIN}
    - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
    - SSL_TYPE=${SSL_TYPE:-letsencrypt}
    - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
    - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
    - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
    ports:
    - ${HTTP_PORT:-80}:80
    - ${HTTPS_PORT:-443}:443
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z localhost 80 || exit 1
    restart: always
    logging:
      driver: local
      options:
        max-file: '30'
    image: ghcr.io/caktus/central-nginx
  pyxform:
    image: ghcr.io/getodk/pyxform-http:v1.12.2
    restart: always
    ports:
    - 80
  secrets:
    volumes:
    - secrets:/etc/secrets
    command: ./generate-secrets.sh
    image: ghcr.io/caktus/central-secrets
  enketo:
    volumes:
    - secrets:/etc/secrets
    restart: always
    depends_on:
    - secrets
    - enketo-redis-main
    - enketo-redis-cache
    environment:
    - DOMAIN=${DOMAIN}
    - SUPPORT_EMAIL=${SYSADMIN_EMAIL}
    - HTTPS_PORT=${HTTPS_PORT:-443}
    ports:
    - 8005
    image: ghcr.io/caktus/central-enketo
  enketo-redis-main:
    image: redis:7.2
    volumes:
    - ./files/enketo/redis-enketo-main.conf:/usr/local/etc/redis/redis.conf:ro
    - enketo_redis_main:/data
    command:
    - redis-server
    - /usr/local/etc/redis/redis.conf
    restart: always
    ports:
    - 6379
  enketo-redis-cache:
    image: redis:7.2
    volumes:
    - ./files/enketo/redis-enketo-cache.conf:/usr/local/etc/redis/redis.conf:ro
    - enketo_redis_cache:/data
    command:
    - redis-server
    - /usr/local/etc/redis/redis.conf
    restart: always
    ports:
    - 6380
volumes:
  secrets: null
  transfer: null
  postgres14: null
  enketo_redis_main: null
  enketo_redis_cache: null

