apiVersion: v1
kind: Secret
metadata:
  name: {{ include "central.fullname" . }}
  labels:
    {{- include "central.labels" . | nindent 4 }}
{{- with .Values.central.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
type: Opaque
