apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.helm.yml -c
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mail
  name: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.helm.yml -c
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/central-default: "true"
        io.kompose.service: mail
    spec:
      containers:
        - env:
            - name: DKIM_KEY_PATH
              value: /etc/exim4/dkim.key.temp
            - name: MAILNAME
          image: ixdotai/smtp:v0.5.1
          name: mail
          ports:
            - containerPort: 25
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/exim4/dkim.key.temp
              name: mail-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mail-claim0
          persistentVolumeClaim:
            claimName: mail-claim0
            readOnly: true
status: {}
